In [19]:
import numpy as np
import pandas as pd        # For loading and processing the dataset
import tensorflow as tf    # Of course, we need TensorFlow.
from sklearn.model_selection import train_test_split

# Read the CSV input file and show first 5 rows
df_train = pd.read_csv('input/train.csv')
df_train.head(5)

# To make 'Sex' numeric, we replace 'female' by 0 and 'male' by 1
df_train['Sex'] = df_train['Sex'].map({'female':0, 'male':1}).astype(int) 

# We replace 'Embarked' by three dummy variables 'Embarked_S', 'Embarked_C', and 'Embarked Q',
# which are 1 if the person embarked there, and 0 otherwise.
df_train = pd.concat([df_train, pd.get_dummies(df_train['Embarked'], prefix='Embarked')], axis=1)
df_train = df_train.drop('Embarked', axis=1)

# We normalize the age and the fare by subtracting their mean and dividing by the standard deviation
age_mean = df_train['Age'].mean()
age_std = df_train['Age'].std()
df_train['Age'] = (df_train['Age'] - age_mean) / age_std

fare_mean = df_train['Fare'].mean()
fare_std = df_train['Fare'].std()
df_train['Fare'] = (df_train['Fare'] - fare_mean) / fare_std

# In many cases, the 'Age' is missing - which can cause problems. Let's look how bad it is:
print("Number of missing 'Age' values: {:d}".format(df_train['Age'].isnull().sum()))

# A simple method to handle these missing values is to replace them by the mean age.
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].mean())

df_train = df_train.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

# With that, we're almost ready for training
df_train.head()

# Finally, we convert the Pandas dataframe to a NumPy array, and split it into a training and test set
X_train = df_train.drop('Survived', axis=1).to_numpy()
y_train = df_train['Survived'].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2)

# We'll build a classifier with two classes: "survived" and "didn't survive",
# so we create the according labels
# This is taken from https://www.kaggle.com/klepacz/titanic/tensor-flow
labels_train = (np.arange(2) == y_train[:,None]).astype(np.float32)
labels_test = (np.arange(2) == y_test[:,None]).astype(np.float32)

Number of missing 'Age' values: 177

In [20]:
df_train.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,-0.530005,1,0,-0.502163,0,0,1
1,1,1,0,0.571430,1,0,0.786404,1,0,0
2,1,3,0,-0.254646,0,0,-0.488580,0,0,1
3,1,1,0,0.364911,1,0,0.420494,0,0,1
4,0,3,1,0.364911,0,0,-0.486064,0,0,1

In [21]:
pd.DataFrame(data=X_train)

       0    1             2    3    4         5    6    7    8
0    3.0  1.0 -7.365243e-01  0.0  0.0 -0.443387  0.0  0.0  1.0
1    2.0  1.0 -1.975639e+00  2.0  1.0  0.136754  0.0  0.0  1.0
2    3.0  1.0  2.003921e-16  1.0  0.0 -0.162078  0.0  1.0  0.0
3    1.0  1.0  1.948225e+00  0.0  2.0  1.631419  1.0  0.0  0.0
4    3.0  1.0 -2.546462e-01  0.0  0.0  0.488829  0.0  0.0  1.0
..   ...  ...           ...  ...  ...       ...  ...  ...  ...
707  3.0  0.0 -1.011883e+00  0.0  0.0 -0.502666  1.0  0.0  0.0
708  3.0  1.0 -6.676845e-01  0.0  0.0 -0.473739  0.0  0.0  1.0
709  1.0  1.0  7.091099e-01  0.0  0.0 -0.648058  0.0  0.0  1.0
710  3.0  1.0 -5.988448e-01  0.0  0.0 -0.491598  0.0  0.0  1.0
711  1.0  1.0  2.960715e-01  0.0  0.0 -0.113782  0.0  0.0  1.0

[712 rows x 9 columns]

In [22]:
for i in range(91):
    X_train = np.hstack((X_train, np.random.uniform(-0.9999999, 0.9999999, 712).reshape(712, 1)))

In [23]:
pd.DataFrame(data=X_train)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,3.0,1.0,-7.365243e-01,0.0,0.0,-0.443387,0.0,0.0,1.0,0.580832,...,-0.086081,0.416002,-0.324563,0.680891,0.465487,0.308194,0.803388,0.622676,-0.012735,0.718276
1,2.0,1.0,-1.975639e+00,2.0,1.0,0.136754,0.0,0.0,1.0,-0.202107,...,0.381529,-0.909387,-0.250939,-0.221426,0.856622,-0.200252,-0.652979,0.027108,-0.262759,-0.901613
2,3.0,1.0,2.003921e-16,1.0,0.0,-0.162078,0.0,1.0,0.0,-0.475773,...,-0.503827,0.321269,-0.914729,0.598506,-0.536833,-0.281248,0.963583,-0.303217,-0.006038,0.679438
3,1.0,1.0,1.948225e+00,0.0,2.0,1.631419,1.0,0.0,0.0,0.975676,...,0.467810,-0.575355,-0.961288,-0.230009,-0.690361,0.260473,0.035860,-0.103837,-0.957852,0.222776
4,3.0,1.0,-2.546462e-01,0.0,0.0,0.488829,0.0,0.0,1.0,0.190923,...,0.619934,-0.969697,0.828104,0.376226,-0.505793,-0.922499,0.827874,-0.383378,0.476507,0.900685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,3.0,0.0,-1.011883e+00,0.0,0.0,-0.502666,1.0,0.0,0.0,0.588086,...,-0.111845,0.166728,0.681929,-0.383587,-0.307156,-0.159276,0.764751,0.444706,0.834060,0.686971
708,3.0,1.0,-6.676845e-01,0.0,0.0,-0.473739,0.0,0.0,1.0,-0.142364,...,0.709206,0.228419,-0.500218,-0.109380,-0.158154,-0.480457,0.441423,-0.715580,0.609093,0.452580
709,1.0,1.0,7.091099e-01,0.0,0.0,-0.648058,0.0,0.0,1.0,0.789351,...,0.124291,0.437982,-0.777802,-0.788200,-0.119609,-0.671220,-0.672999,0.186308,0.158429,-0.614474
710,3.0,1.0,-5.988448e-01,0.0,0.0,-0.491598,0.0,0.0,1.0,-0.739746,...,-0.301138,-0.548657,0.683999,-0.831769,0.859881,0.597380,0.251840,-0.687958,-0.977974,0.941763
711,1.0,1.0,2.960715e-01,0.0,0.0,-0.113782,0.0,0.0,1.0,-0.686476,...,0.725030,-0.010442,-0.142377,0.768188,0.595682,0.346069,-0.425599,0.742192,0.197773,-0.986017

In [24]:
model = tf.keras.Sequential([
    # tf.keras.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(2, activation='softmax')
])

model.compile(
  optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
  loss=tf.keras.losses.BinaryCrossentropy(
    from_logits=True, label_smoothing=0, reduction="auto", name="binary_crossentropy"),
  metrics=['accuracy'],
)

In [25]:
x = model.layers[4].get_weights()

In [26]:
tbCallBack = tf.keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=0, write_graph=True, write_images=True)
model.fit(
  X_train,
  labels_train, # training targets
  epochs=50,
  callbacks=[tbCallBack]
)

Epoch 1/50
 1/23 [>.............................] - ETA: 0s - loss: 0.7345 - accuracy: 0.4375WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0015s vs `on_train_batch_end` time: 0.0198s). Check your callbacks.
23/23 [==============================] - 0s 2ms/step - loss: 0.7145 - accuracy: 0.5744
Epoch 2/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7066 - accuracy: 0.5702
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7080 - accuracy: 0.5899
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7045 - accuracy: 0.5927
Epoch 5/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7047 - accuracy: 0.5899
Epoch 6/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7017 - accuracy: 0.6025
Epoch 7/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7011 - accuracy: 0.6250
Epoch 8/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7001 - accuracy: 0.5997
Epoch 9/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7013 - accuracy: 0.5899
Epoch 10/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7022 - accuracy: 0.5955
Epoch 11/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6990 - accuracy: 0.6124
Epoch 12/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6970 - accuracy: 0.6138
Epoch 13/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6969 - accuracy: 0.6053
Epoch 14/50
23/23 [==============================] - 0s 2ms/step - loss: 0.7010 - accuracy: 0.5997
Epoch 15/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6958 - accuracy: 0.6025
Epoch 16/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6982 - accuracy: 0.5969
Epoch 17/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6958 - accuracy: 0.5997
Epoch 18/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6977 - accuracy: 0.6096
Epoch 19/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6964 - accuracy: 0.6011
Epoch 20/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.6067
Epoch 21/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6968 - accuracy: 0.6067
Epoch 22/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6984 - accuracy: 0.6039
Epoch 23/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.6053
Epoch 24/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6968 - accuracy: 0.6025
Epoch 25/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6958 - accuracy: 0.6039
Epoch 26/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6961 - accuracy: 0.6067
Epoch 27/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6935 - accuracy: 0.6039
Epoch 28/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6936 - accuracy: 0.6081
Epoch 29/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.5969
Epoch 30/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6922 - accuracy: 0.6110
Epoch 31/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.6025
Epoch 32/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6922 - accuracy: 0.6110
Epoch 33/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6899 - accuracy: 0.6138
Epoch 34/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6914 - accuracy: 0.6152
Epoch 35/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6931 - accuracy: 0.6138
Epoch 36/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6890 - accuracy: 0.6081
Epoch 37/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6883 - accuracy: 0.6166
Epoch 38/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6878 - accuracy: 0.6166
Epoch 39/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.6096
Epoch 40/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6917 - accuracy: 0.6152
Epoch 41/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6902 - accuracy: 0.6194
Epoch 42/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6894 - accuracy: 0.6096
Epoch 43/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.6053
Epoch 44/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6928 - accuracy: 0.6180
Epoch 45/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6908 - accuracy: 0.6124
Epoch 46/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6870 - accuracy: 0.6096
Epoch 47/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6897 - accuracy: 0.6180
Epoch 48/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6907 - accuracy: 0.6096
Epoch 49/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6909 - accuracy: 0.6138
Epoch 50/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6885 - accuracy: 0.6067

In [28]:
import keras
model.save('./simple_ff.h5')